# Generated by Django 3.2.7 on 2021-09-24 17:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batchit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comforques',
            name='question',
        ),
        migrations.RemoveField(
            model_name='comforques',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='com_desc',
            new_name='ans_desc',
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_auth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ComForAns',
        ),
        migrations.DeleteModel(
            name='ComForQues',
        ),
        migrations.AddField(
            model_name='comments',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comforans', to='batchit.answer'),
        ),
        migrations.AddField(
            model_name='comments',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comforques', to='batchit.question'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_ath', to=settings.AUTH_USER_MODEL),
        ),
    ]
